### ISSUE TITLE
关于urls的配置

### ISSUE THREAD

**Issue by bugknightyyp** [wayfind/flex-combo#11]
我认为关于`function(prjDir, urls, options)`形式参数写成`function(prjDir,  options)`的形式比较好，参数urls作为options字段就好，所有的配置参数都可以放到一个对象里放到一个配置文件里，稍微简洁方便点。可能你认为一般情况下只有urls需要配置，其他参数使用默认的就好，所以把urls单独提出来了。

**Comment by limingv5** [comment]
新版已重构
