### ISSUE TITLE
配置 prefix

### ISSUE THREAD

**Issue by xcatliu** [wayfind/flex-combo#14]
http://127.0.0.1:1337/test/js/??js1.js,js2.js,js3.js

请问有配置可以去掉前缀 ?? 吗

http://127.0.0.1:1337/test/js/js1.js,js2.js,js3.js

**Comment by limingv5** [comment]
??用来识别淘系combo的标识，如果要实现你的需求，建议通过defineParser方法，自行定义url解析逻辑
