### ISSUE TITLE
服务开启后，无法获取最近更新的文件

### ISSUE THREAD

**Issue by yaoboqin** [wayfind/flex-combo#46]
之前一直使用的是0.6.7版本
最近升级到最新版本0.12.12

对项目目录下某一个js文件更新后
0.6.7版本显示的是最新文件
0.12.12版本显示的仍旧是未更新的文件
服务重启后才可获取最新文件，不知何解

**Comment by limingv5** [comment]
@yaoboqin 方便把工程目录和flex-combo配置文件打包发送给我吗？或者具体描述一下？（limingv5#gmail.com，#=>@）

**Comment by yaoboqin** [comment]
https://github.com/tbtx/static-server
原版"flex-combo": "^0.6.7"ok，
"flex-combo": "*"
会出现我说的那个问题

**Comment by limingv5** [comment]
@yaoboqin 已经向你的项目发起了pull request，感谢使用flex-combo！
